export const NIGERIAN_STATES = [
  "Lagos", "Abuja (FCT)", "Rivers (Port Harcourt)", "Oyo (Ibadan)", "Kano",
  "Ogun", "Enugu", "Delta", "Anambra", "Kaduna", "Edo", "Abia", "Adamawa",
  "Akwa Ibom", "Bauchi", "Bayelsa", "Benue", "Borno", "Cross River", "Ebonyi",
  "Ekiti", "Gombe", "Imo", "Jigawa", "Katsina", "Kebbi", "Kogi", "Kwara",
  "Nasarawa", "Niger", "Ondo", "Osun", "Plateau", "Sokoto", "Taraba", "Yobe", "Zamfara"
];

export const BUSINESS_CATEGORIES = [
  "Supermarket / Hypermarket",
  "Pharmacy & Health Store",
  "Neighborhood Mini-Mart",
  "FMCG Wholesaler",
  "Food Distributor",
  "Bakery & Pastry Shop",
  "Restaurant & Catering",
  "Other Retailer"
];

export const NAV_ITEMS = [
  { label: "Flash Deals", href: "#marketplace" },
  { label: "How It Works", href: "#how-it-works" },
  { label: "For Merchants", href: "#vendor-demo" },
  { label: "Savings Calculator", href: "#calculator" },
  { label: "Why Us", href: "#why-us" },
  { label: "FAQs", href: "#faqs" },
];

export const PRODUCT_CATEGORIES = [
  { id: "all", name: "All Deals", icon: "🔥", color: "#FF6B00" },
  { id: "dairy", name: "Dairy & Eggs", icon: "🥛", color: "#0F8B4C" },
  { id: "beverages", name: "Drinks & Juices", icon: "🥤", color: "#2563EB" },
  { id: "bakery", name: "Bakery & Snacks", icon: "🥐", color: "#D97706" },
  { id: "pantry", name: "Pantry & Oils", icon: "🫒", color: "#7C3AED" },
  { id: "breakfast", name: "Cereals & Coffee", icon: "☕", color: "#06B6D4" },
  { id: "health", name: "Personal Care", icon: "🧴", color: "#EC4899" },
];

export const MOCK_CLEARANCE_PRODUCTS = [
  {
    id: "prod-1",
    name: "Peak Organic Whole Milk (Pack of 6)",
    category: "dairy",
    storeName: "Shoprite Mega Mall, Ikeja",
    storeLocation: "Lagos",
    storeVerified: true,
    originalPrice: 4800,
    clearancePrice: 1450,
    discountPercent: 70,
    daysLeft: 3,
    expiryDate: "Aug 5, 2026",
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80",
    unit: "6 x 1L Pack",
    stockRemaining: 14,
    badge: "SUPER DEAL",
  },
  {
    id: "prod-2",
    name: "Fresh Pressed Citrus Orange Juice",
    category: "beverages",
    storeName: "SPAR Supermarket, VI",
    storeLocation: "Lagos",
    storeVerified: true,
    originalPrice: 3200,
    clearancePrice: 950,
    discountPercent: 70,
    daysLeft: 2,
    expiryDate: "Aug 4, 2026",
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80",
    unit: "1L Glass Bottle",
    stockRemaining: 8,
    badge: "80% OFF",
  },
  {
    id: "prod-3",
    name: "Artisan Organic Whole Wheat Sourdough",
    category: "bakery",
    storeName: "Hubmart Stores, Lekki Phase 1",
    storeLocation: "Lagos",
    storeVerified: true,
    originalPrice: 2500,
    clearancePrice: 600,
    discountPercent: 76,
    daysLeft: 1,
    expiryDate: "Aug 3, 2026",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80",
    unit: "800g Loaf",
    stockRemaining: 5,
    badge: "NEAR DUE-DATE TOMORROW",
  },
  {
    id: "prod-4",
    name: "Berry & Honey Honey Crunch Granola",
    category: "breakfast",
    storeName: "Ebeano Supermarket, Chevron",
    storeLocation: "Lagos",
    storeVerified: true,
    originalPrice: 6500,
    clearancePrice: 2100,
    discountPercent: 68,
    daysLeft: 5,
    expiryDate: "Aug 7, 2026",
    image: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&w=600&q=80",
    unit: "500g Box",
    stockRemaining: 22,
    badge: "POPULAR",
  },
  {
    id: "prod-5",
    name: "Extra Virgin Olive Oil (First Cold Press)",
    category: "pantry",
    storeName: "Grand Square, Central Area",
    storeLocation: "Abuja",
    storeVerified: true,
    originalPrice: 9800,
    clearancePrice: 3400,
    discountPercent: 65,
    daysLeft: 7,
    expiryDate: "Aug 9, 2026",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80",
    unit: "750ml Bottle",
    stockRemaining: 11,
    badge: "TOP QUALITY",
  },
  {
    id: "prod-6",
    name: "Gourmet Dark Chocolate 72% Cocoa",
    category: "bakery",
    storeName: "Next Cash & Carry",
    storeLocation: "Abuja",
    storeVerified: true,
    originalPrice: 3800,
    clearancePrice: 1100,
    discountPercent: 71,
    daysLeft: 4,
    expiryDate: "Aug 6, 2026",
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=600&q=80",
    unit: "3 x 100g Bars",
    stockRemaining: 19,
    badge: "70% OFF",
  },
  {
    id: "prod-7",
    name: "Dark Roasted Whole Arabica Beans",
    category: "breakfast",
    storeName: "Market Square, GRA",
    storeLocation: "Port Harcourt",
    storeVerified: true,
    originalPrice: 8500,
    clearancePrice: 2800,
    discountPercent: 67,
    daysLeft: 6,
    expiryDate: "Aug 8, 2026",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=600&q=80",
    unit: "500g Bag",
    stockRemaining: 9,
    badge: "FRESHLY ROASTED",
  },
  {
    id: "prod-8",
    name: "Authentic Greek Honey Yogurt",
    category: "dairy",
    storeName: "Justrite Store, Ota",
    storeLocation: "Ogun",
    storeVerified: true,
    originalPrice: 2800,
    clearancePrice: 750,
    discountPercent: 73,
    daysLeft: 2,
    expiryDate: "Aug 4, 2026",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80",
    unit: "450g Tub",
    stockRemaining: 16,
    badge: "FLASH DEAL",
  },
];

export const TRUST_BRANDS = [
  { name: "Shoprite", count: "12 Stores" },
  { name: "SPAR Nigeria", count: "8 Stores" },
  { name: "Hubmart", count: "5 Stores" },
  { name: "Ebeano", count: "7 Stores" },
  { name: "Justrite", count: "14 Stores" },
  { name: "Market Square", count: "9 Stores" },
];

export const WHY_BESTBEFORE = [
  {
    title: "Save Up To 85% On Groceries",
    description: "Access premium brand items nearing their best-before date at a fraction of their retail price.",
    icon: "💰",
  },
  {
    title: "Zero Food Waste Movement",
    description: "Prevent tons of perfectly safe, high-quality groceries from ending up in landfills every month.",
    icon: "🌱",
  },
  {
    title: "Turn Loss Into Revenue",
    description: "Supermarkets and distributors liquidate stock before expiration to recover cash flow immediately.",
    icon: "📈",
  },
  {
    title: "100% Quality & Safety Guarantee",
    description: "All products listed are strictly inspected and compliant with NAFDAC best-before safety guidelines.",
    icon: "🛡️",
  },
];

export const TESTIMONIALS = [
  {
    name: "Chidimma Okafor",
    role: "Mother of 3, Lagos",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    text: "I saved over ₦65,000 on cereals, milk, and cooking oil last month alone! The items are perfectly fresh and packaged.",
    rating: 5,
    badge: "Verified Buyer",
  },
  {
    name: "Babajide Martins",
    role: "Inventory Manager, Shoprite Ikeja",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    text: "Best Before turned our expiring stock into over ₦4.2M in recovered revenue in 60 days. It takes under 30 seconds to post items!",
    rating: 5,
    badge: "Verified Store Merchant",
  },
  {
    name: "Amina Yusuf",
    role: "University Student, Abuja",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
    text: "As a student on a budget, getting premium chocolates, juices, and snacks at 75% discount is a absolute game changer!",
    rating: 5,
    badge: "Verified VIP Shopper",
  },
];

export const HOW_IT_WORKS = [
  { step: 1, title: "Store Scans Stock", description: "Supermarkets, pharmacies and stores list products approaching their best-before date in 30 seconds." },
  { step: 2, title: "Price Auto-Discounted", description: "System calculates 50% to 85% discount depending on days remaining before expiry." },
  { step: 3, title: "Shoppers Discover", description: "Budget-conscious shoppers find local clearance deals on fresh milk, juices, cereals, and groceries." },
  { step: 4, title: "Instant Reserve & Pay", description: "Shoppers reserve items online for fast local pickup or express delivery in Lagos & Abuja." },
  { step: 5, title: "Stores Recover Cash", description: "Supermarkets convert write-off losses into immediate liquid revenue before items expire." },
  { step: 6, title: "Zero Food Waste", description: "Tons of perfectly safe, high-quality groceries stay out of landfills, protecting the planet." },
];

